#!/bin/bash

set -x

#Move .env where it needs to be
mv api_env api/.env

# Don't need it anymore
rm git_rsa.enc

# Ensure perms are a go
chmod 600 git_rsa

# Make key default
mv git_rsa ~/.ssh/id_rsa
