#!/bin/bash

# Check if .env file exists
# if [ -e .env ]; then
#     source .env
# else
#     echo "Error: please ensure your .env file has been configured"
#     exit 1
# fi

printf "\n\n\nGot here...\n\n\n"
